spring:
  application:
    name: jwt-spring-boot

  datasource:
    url: jdbc:postgresql://localhost:5432/jwtdb
    username: "postgres"
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  private-key-path: C:/Users/PC/Documents/private_key.pem
  public-key-path: C:/Users/PC/Documents/public_key.pem
  passphrase: loula4312